apiVersion: v1
kind: Service
metadata:
  name: tp-2025-service
spec:
  type: NodePort
  selector:
    app: tp-2025
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30007
    - name: extra
      port: 9091
      targetPort: 9091
